name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Foo
      if: github.pull_request
      run: echo "Foo"
    - name: Foo
      if: not github.pull_request
      run: echo "Bar"
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
