name: Test clang
on: workflow_dispatch
jobs:
  build:
    name: test different clangs
    runs-on: macos-latest    
    steps:
    - name: test clang
      shell: bash
      run: |
        which clang++
        clang++ --version

        $(brew --prefix llvm@15)/bin/clang++ --version || true

        $(brew --prefix llvm@14)/bin/clang++ --version || true

        xcodebuild -find clang++
        $(xcodebuild -find clang++) --version
