name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: windows-latest    
    steps:
      - uses: actions/checkout@v2
        with:
          path: test
      - name: Configure x64 environment
        run: test\.github\workflows\vsenv.bat -arch=x64 -host_arch=x64
      - name: Install Miniconda
        shell: bash # uses git bash on windows
        run: |
            MINICONDA_FILENAME=Miniconda3-latest-Windows-x86_64.exe
            curl -o $MINICONDA_FILENAME "https://repo.anaconda.com/miniconda/$MINICONDA_FILENAME"
            ./Miniconda3-latest-Windows-x86_64.exe //InstallationType=JustMe //RegisterPython=0 //S //D=$HOME/miniconda3
      - name: Setup conda paths
        shell: bash
        run: |
          echo "::add-path::$HOME/miniconda3/bin"
          echo "::add-path::$HOME/miniconda3/Scripts"
      - name: test
        shell: bash
        run: |
          conda create -n test python=3.7
          source activate test
          # set current python executable
          CURRENT_PYTHON_EXECUTABLE=$(which python)
          ${CURRENT_PYTHON_EXECUTABLE} -m pip install --upgrade pip
          # pip install all the stuff
          pip install -U setuptools
          pip install -U pip
          pip install -U autowrap
          pip install -U nose
          pip install -U numpy
          pip install -U wheel
          # conda deactivate
          
          python --version
          python -c "from setuptools import msvc; print(msvc._msvc14_find_vc2017())"
          python -c "from setuptools import msvc; print(msvc._msvc14_find_vcvarsall('amd64'))"
          python -c "from setuptools import msvc; print(msvc.msvc14_get_vc_env('amd64'))"
          python -c "from setuptools import msvc; print(msvc.msvc9_query_vcvarsall(14.0, 'x64'))"
          cd test
          python setup.py build
