name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: windows-latest    
    steps:
      - name: Configure x64 environment
        run: OpenMS\.github\workflows\vsenv.bat -arch=x64 -host_arch=x64
      - run: |
          pip install -U setuptools
          python --version
          python -c "from setuptools import msvc; msvc.msvc9_query_vcvarsall(14.0, 'x64')"
