name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: windows-latest    
    steps:
      - run: |
          pip install -U setuptools
          python -c "from setuptools import msvc; msvc.msvc9_query_vcvarsall(14.0, 'x64')"
